FROM oven/bun:1.0.30-debian

# Needed for the node:child_process module, TODO: maybe replace it with a bun specific module in the future
RUN apt-get update && apt-get install -y build-essential

WORKDIR /app

COPY package.json .
COPY bun.lockb .

RUN bun install --production

# .env is only copied for development/testing (not available in remote repo => not copied in production), production has it's own way of setting environment variables for the application
COPY **.env .env
RUN [ -s .env ] || rm .env
COPY src src
COPY static static
COPY tsconfig.json .

ENV NODE_ENV production
CMD ["bun", "src/index.ts"]

EXPOSE 80
