FROM oven/bun:1.0.30-debian

# Needed for the node:child_process module, TODO: maybe replace it with a bun specific module in the future
RUN apt-get update && apt-get install -y build-essential

WORKDIR /app

COPY package.json .
COPY bun.lockb .

RUN bun install --production

COPY src src
COPY static static
COPY tsconfig.json .

ENV NODE_ENV production
CMD ["bun", "src/index.ts"]

EXPOSE 80
