name: Continuous Deployment - Rest Backend Service
on:
  workflow_run:
    workflows: ["Continuous Integration - Rest Backend Service"]
    types:
      - completed
permissions: write-all

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: Dockerfile.web
          push: true
          tags: |
            propromo/rest-microservice:latest
            ghcr.io/${{ github.repository_owner }}/propromo-rest-microservice:latest

#
# HEROKU DEPLOYMENT
#      - name: Build, Push and Deploy to Heroku
#        id: heroku
#        uses: jctaveras/heroku-deploy@v3.1.0
#        with:
#          email: ${{ secrets.HEROKU_EMAIL }}
#          api_key: ${{ secrets.HEROKU_API_KEY }}
#          app_name: ${{ secrets.HEROKU_APP_NAME }}
#          dockerfile_path: '.'
#          process_type: 'web'
#
