name: Continuous Integration - Rest Backend Service
on: ["push", "pull_request"]

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Environment
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Setup Bun Environment
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.36

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test
