name: Continuous Integration - Rest Backend Service
on: ["push", "pull_request"]

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Environment
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Setup Bun Environment
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.36

      - name: Install dependencies
        run: bun install

      - name: Run tests
        env:
          DEV_MODE: true
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          DEV_ACCESS_PASSPHRASE: ${{ secrets.DEV_ACCESS_PASSPHRASE }}

          GITHUB_APP_CLIENT_ID: ${{ secrets.GH_APP_CLIENT_ID }}
          GITHUB_APP_CLIENT_SECRET: ${{ secrets.GH_APP_CLIENT_SECRET }}
          GITHUB_APP_ID: ${{ secrets.GH_APP_ID }}
          GITHUB_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
          GITHUB_APP_WEBHOOK_SECRET: ${{ secrets.GH_APP_WEBHOOK_SECRET }}
        run: bun test --coverage

      # TODO: waiting for bun to support coverage report formats
      #- name: Update Coverage Badge
      #  # GitHub actions: default branch variable
      #  # https://stackoverflow.com/questions/64781462/github-actions-default-branch-variable
      #  if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      #  uses: we-cli/coverage-badge-action@main
