name: Sync Database Schemas

on:
  schedule:
    - cron: "*/10 * * * *" # check every 10 minutes

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      DATABASE_MAIN_HOST: ${{ secrets.DATABASE_MAIN_HOST }}
      DATABASE_NEXT_HOST: ${{ secrets.DATABASE_NEXT_HOST }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Fuck you and your trashy lockfile bun, and fuck you for saying you are a drop-in replacement even though you are absolutely fucking not. Fuck you.
      # https://github.com/drizzle-team/drizzle-orm/issues/2239
      - name: Yarn setup
        uses: DerYeger/yarn-setup-action@2.0.21
        with:
          node-version: 18

      # The part of the action that would be enough, if bun wasn't such a bitch, not supporting basic stuff.
      - name: Install dependencies
        run: yarn ci

      - name: Pull Schemas
        run: |
          drizzle-kit introspect:pg --config drizzle.config.main.ts
          drizzle-kit introspect:pg --config drizzle.config.next.ts

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6

      - name: Log Pull Request Info
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
